// <auto-generated />
using System;
using ControlBiblioteca.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ControlBiblioteca.Migrations
{
    [DbContext(typeof(BIBLIOTECAContext))]
    partial class BIBLIOTECAContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ControlBiblioteca.Models.Autor", b =>
                {
                    b.Property<int>("AutorId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("AutorID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AutorId"));

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(256)
                        .IsUnicode(false)
                        .HasColumnType("varchar(256)");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasMaxLength(2)
                        .IsUnicode(false)
                        .HasColumnType("varchar(2)");

                    b.Property<DateTime?>("FechaCreacion")
                        .HasColumnType("datetime");

                    b.HasKey("AutorId")
                        .HasName("PK__AUTOR__F58AE909ACD96785");

                    b.ToTable("AUTOR", (string)null);
                });

            modelBuilder.Entity("ControlBiblioteca.Models.ErrorLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Controller")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Endpoint")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ErrorMessage")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ErrorStackTrace")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("ErrorTimestamp")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("ErrorLogs");
                });

            modelBuilder.Entity("ControlBiblioteca.Models.GeneroLiterario", b =>
                {
                    b.Property<int>("GeneroLiterarioID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("GeneroLiterarioID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("GeneroLiterarioID"));

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(256)
                        .IsUnicode(false)
                        .HasColumnType("varchar(256)");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasMaxLength(2)
                        .IsUnicode(false)
                        .HasColumnType("varchar(2)");

                    b.Property<DateTime?>("FechaCreacion")
                        .HasColumnType("datetime");

                    b.HasKey("GeneroLiterarioID")
                        .HasName("PK__GENERO_L__5B6322709BE81B8B");

                    b.ToTable("GENERO_LITERARIO", (string)null);
                });

            modelBuilder.Entity("ControlBiblioteca.Models.Libro", b =>
                {
                    b.Property<int>("LibroId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("LibroID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("LibroId"));

                    b.Property<int>("AutorId")
                        .HasColumnType("int")
                        .HasColumnName("AutorID");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasMaxLength(2)
                        .IsUnicode(false)
                        .HasColumnType("varchar(2)");

                    b.Property<DateTime?>("FechaCreacion")
                        .HasColumnType("datetime");

                    b.Property<int>("GeneroLiterarioId")
                        .HasColumnType("int")
                        .HasColumnName("GeneroLiterarioID");

                    b.Property<string>("NombreLibro")
                        .IsRequired()
                        .HasMaxLength(256)
                        .IsUnicode(false)
                        .HasColumnType("varchar(256)");

                    b.HasKey("LibroId")
                        .HasName("PK__LIBRO__35A1EC8D202E18EE");

                    b.HasIndex("AutorId");

                    b.HasIndex("GeneroLiterarioId");

                    b.ToTable("LIBRO", (string)null);
                });

            modelBuilder.Entity("ControlBiblioteca.Models.Parametro", b =>
                {
                    b.Property<int>("ParametroId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ParametroID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ParametroId"));

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(250)
                        .IsUnicode(false)
                        .HasColumnType("varchar(250)");

                    b.Property<string>("Valor")
                        .IsRequired()
                        .IsUnicode(false)
                        .HasColumnType("varchar(max)");

                    b.HasKey("ParametroId")
                        .HasName("PK__PARAMETR__2B3CE672E26A000B");

                    b.ToTable("PARAMETRO", (string)null);
                });

            modelBuilder.Entity("ControlBiblioteca.Models.Libro", b =>
                {
                    b.HasOne("ControlBiblioteca.Models.Autor", "Autor")
                        .WithMany("Libros")
                        .HasForeignKey("AutorId")
                        .IsRequired()
                        .HasConstraintName("FK__LIBRO__AutorID__3C69FB99");

                    b.HasOne("ControlBiblioteca.Models.GeneroLiterario", "GeneroLiterario")
                        .WithMany("Libros")
                        .HasForeignKey("GeneroLiterarioId")
                        .IsRequired()
                        .HasConstraintName("FK__LIBRO__GeneroLit__3B75D760");

                    b.Navigation("Autor");

                    b.Navigation("GeneroLiterario");
                });

            modelBuilder.Entity("ControlBiblioteca.Models.Autor", b =>
                {
                    b.Navigation("Libros");
                });

            modelBuilder.Entity("ControlBiblioteca.Models.GeneroLiterario", b =>
                {
                    b.Navigation("Libros");
                });
#pragma warning restore 612, 618
        }
    }
}
